In [1]:
import numpy as np

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

# Add another NumPy array, multiply element-wise with x, and print results:
y = np.arange(1, 16, dtype=np.int64).reshape(3, 5)
product = x * y
print("Second array (y):")
print(y)
print("Element-wise multiplication result (x * y):")
print(product)


array([ 2.37085995,  0.69745139,  0.57601507, ..., -0.21107466,
       -0.99124658,  2.71312193], shape=(2500,))